"""Generate supabase/seed.sql from data/measures.json.

Usage (PowerShell):  python scripts/build_seed.py
Re-run any time you edit data/measures.json. The SQL is idempotent (upserts).
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
data = json.loads((ROOT / "data" / "measures.json").read_text(encoding="utf-8"))

ELECTION_ID = "ca-2026-11"


def q(v):
    """SQL-quote a scalar or JSON-able value."""
    if v is None:
        return "null"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, (list, dict)):
        return q(json.dumps(v, ensure_ascii=False)) + "::jsonb"
    return "'" + str(v).replace("'", "''") + "'"


out = []
e = data["election"]
out.append("-- Generated by scripts/build_seed.py — do not hand-edit; edit data/measures.json instead.\n")
out.append("begin;\n")
out.append(
    f"insert into elections (id, name, election_date, official_guide_url, funding_as_of) values "
    f"({q(ELECTION_ID)}, {q(e['name'])}, {q(e['date'])}, {q(e['official_guide'])}, {q(e['funding_as_of'])}) "
    "on conflict (id) do update set name=excluded.name, election_date=excluded.election_date, "
    "official_guide_url=excluded.official_guide_url, funding_as_of=excluded.funding_as_of;\n"
)

for m in data["measures"]:
    cols = {
        "election_id": ELECTION_ID,
        "number": m["number"],
        "slug": m["slug"],
        "short_title": m["short_title"],
        "official_title": m["official_title"],
        "type": m.get("type"),
        "origin": m.get("origin"),
        "what_it_does": m.get("what_it_does"),
        "yes_means": m.get("yes_means"),
        "no_means": m.get("no_means"),
        "fiscal_impact": m.get("fiscal_impact"),
        "pro_arguments": m.get("pro_arguments", []),
        "con_arguments": m.get("con_arguments", []),
        "leaves_out_yes": m.get("leaves_out", {}).get("yes", []),
        "leaves_out_no": m.get("leaves_out", {}).get("no", []),
        "campaign_links": m.get("campaign_links", {}),
        "sources": m.get("sources", []),
        "published": True,
    }
    names = ", ".join(cols)
    vals = ", ".join(q(v) for v in cols.values())
    updates = ", ".join(f"{k}=excluded.{k}" for k in cols if k not in ("election_id", "number"))
    out.append(
        f"insert into measures ({names}) values ({vals}) "
        f"on conflict (election_id, number) do update set {updates}, updated_at=now();\n"
    )
    # committees: replace wholesale for this measure
    out.append(f"delete from committees where measure_id = (select id from measures where slug={q(m['slug'])});\n")
    for i, c in enumerate(m.get("committees", [])):
        out.append(
            "insert into committees (measure_id, side, name, fppc_id, top_funders, raised, sort_order) values ("
            f"(select id from measures where slug={q(m['slug'])}), {q(c['side'])}, {q(c['name'])}, "
            f"{q(c.get('fppc_id'))}, {q(c.get('top_funders', []))}, {q(c.get('raised'))}, {i});\n"
        )

by_number = {m["number"]: m["slug"] for m in data["measures"]}
for a in data["ads"]:
    slug = by_number[a["measure"]]
    out.append(
        "insert into ads (id, measure_id, side, title, sponsor, format, url, transcript, first_seen, status) values ("
        f"{q(a['id'])}, (select id from measures where slug={q(slug)}), {q(a['side'])}, {q(a['title'])}, "
        f"{q(a.get('sponsor'))}, {q(a.get('format'))}, {q(a.get('url'))}, {q(a.get('transcript'))}, "
        f"{q(a.get('first_seen'))}, {q(a.get('status', 'draft'))}) "
        "on conflict (id) do update set measure_id=excluded.measure_id, side=excluded.side, title=excluded.title, "
        "sponsor=excluded.sponsor, format=excluded.format, url=excluded.url, transcript=excluded.transcript, "
        "first_seen=excluded.first_seen, status=excluded.status;\n"
    )
    out.append(f"delete from claims where ad_id={q(a['id'])};\n")
    for i, c in enumerate(a.get("claims", [])):
        out.append(
            "insert into claims (ad_id, claim, context, source_url, sort_order) values ("
            f"{q(a['id'])}, {q(c['claim'])}, {q(c['context'])}, {q(c.get('source_url'))}, {i});\n"
        )

out.append("commit;\n")
(ROOT / "supabase" / "seed.sql").write_text("".join(out), encoding="utf-8")
print(f"wrote supabase/seed.sql: {len(data['measures'])} measures, {len(data['ads'])} ads")
